# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - graphql/schema/*.graphql

# Where should the generated server code go?
exec:
  filename: graphql/generated/generated.go
  package: generated

struct_tag: json

# Where should any generated models go?
model:
  filename: graphql/model/models_gen.go
  package: model

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: graphql/resolver
  package: resolver

autobind:
  - "github.com/CristhoperDev/go-graphql-entc/graphql/model"

# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32

  # model
  Author:
    model:
      - github.com/CristhoperDev/go-graphql-entc/internal/provider/entc.Author
    fields:
      film:
        resolver: true

  Film:
    model:
      - github.com/CristhoperDev/go-graphql-entc/internal/provider/entc.Film
    fields:
      author:
        resolver: true