// Code generated by entc, DO NOT EDIT.

package entc

import (
	"fmt"
	"strings"
	"time"

	"github.com/CristhoperDev/go-graphql-entc/internal/provider/entc/film"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/google/uuid"
)

// Film is the model entity for the Film schema.
type Film struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status int8 `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FilmQuery when eager-loading is set.
	Edges FilmEdges `json:"edges"`
}

// FilmEdges holds the relations/edges for other nodes in the graph.
type FilmEdges struct {
	// Authors holds the value of the authors edge.
	Authors []*Author
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AuthorsOrErr returns the Authors value or an error if the edge
// was not loaded in eager-loading.
func (e FilmEdges) AuthorsOrErr() ([]*Author, error) {
	if e.loadedTypes[0] {
		return e.Authors, nil
	}
	return nil, &NotLoadedError{edge: "authors"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Film) scanValues() []interface{} {
	return []interface{}{
		&uuid.UUID{},      // id
		&sql.NullInt64{},  // status
		&sql.NullTime{},   // created_at
		&sql.NullTime{},   // updated_at
		&sql.NullString{}, // title
		&sql.NullString{}, // description
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Film fields.
func (f *Film) assignValues(values ...interface{}) error {
	if m, n := len(values), len(film.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	if value, ok := values[0].(*uuid.UUID); !ok {
		return fmt.Errorf("unexpected type %T for field id", values[0])
	} else if value != nil {
		f.ID = *value
	}
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field status", values[0])
	} else if value.Valid {
		f.Status = int8(value.Int64)
	}
	if value, ok := values[1].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field created_at", values[1])
	} else if value.Valid {
		f.CreatedAt = value.Time
	}
	if value, ok := values[2].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field updated_at", values[2])
	} else if value.Valid {
		f.UpdatedAt = value.Time
	}
	if value, ok := values[3].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field title", values[3])
	} else if value.Valid {
		f.Title = value.String
	}
	if value, ok := values[4].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field description", values[4])
	} else if value.Valid {
		f.Description = value.String
	}
	return nil
}

// QueryAuthors queries the authors edge of the Film.
func (f *Film) QueryAuthors() *AuthorQuery {
	return (&FilmClient{config: f.config}).QueryAuthors(f)
}

// Update returns a builder for updating this Film.
// Note that, you need to call Film.Unwrap() before calling this method, if this Film
// was returned from a transaction, and the transaction was committed or rolled back.
func (f *Film) Update() *FilmUpdateOne {
	return (&FilmClient{config: f.config}).UpdateOne(f)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (f *Film) Unwrap() *Film {
	tx, ok := f.config.driver.(*txDriver)
	if !ok {
		panic("entc: Film is not a transactional entity")
	}
	f.config.driver = tx.drv
	return f
}

// String implements the fmt.Stringer.
func (f *Film) String() string {
	var builder strings.Builder
	builder.WriteString("Film(")
	builder.WriteString(fmt.Sprintf("id=%v", f.ID))
	builder.WriteString(", status=")
	builder.WriteString(fmt.Sprintf("%v", f.Status))
	builder.WriteString(", created_at=")
	builder.WriteString(f.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(f.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", title=")
	builder.WriteString(f.Title)
	builder.WriteString(", description=")
	builder.WriteString(f.Description)
	builder.WriteByte(')')
	return builder.String()
}

// Films is a parsable slice of Film.
type Films []*Film

func (f Films) config(cfg config) {
	for _i := range f {
		f[_i].config = cfg
	}
}
