// Code generated by entc, DO NOT EDIT.

package entc

import (
	"time"

	"github.com/CristhoperDev/go-graphql-entc/internal/provider/entc/author"
	"github.com/CristhoperDev/go-graphql-entc/internal/provider/entc/film"
	"github.com/CristhoperDev/go-graphql-entc/internal/provider/entc/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	authorMixin := schema.Author{}.Mixin()
	authorMixinFields0 := authorMixin[0].Fields()
	authorMixinFields1 := authorMixin[1].Fields()
	authorFields := schema.Author{}.Fields()
	_ = authorFields
	// authorDescStatus is the schema descriptor for status field.
	authorDescStatus := authorMixinFields0[1].Descriptor()
	// author.DefaultStatus holds the default value on creation for the status field.
	author.DefaultStatus = authorDescStatus.Default.(int8)
	// authorDescCreatedAt is the schema descriptor for created_at field.
	authorDescCreatedAt := authorMixinFields1[0].Descriptor()
	// author.DefaultCreatedAt holds the default value on creation for the created_at field.
	author.DefaultCreatedAt = authorDescCreatedAt.Default.(func() time.Time)
	// authorDescUpdatedAt is the schema descriptor for updated_at field.
	authorDescUpdatedAt := authorMixinFields1[1].Descriptor()
	// author.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	author.DefaultUpdatedAt = authorDescUpdatedAt.Default.(func() time.Time)
	// author.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	author.UpdateDefaultUpdatedAt = authorDescUpdatedAt.UpdateDefault.(func() time.Time)
	filmMixin := schema.Film{}.Mixin()
	filmMixinFields0 := filmMixin[0].Fields()
	filmMixinFields1 := filmMixin[1].Fields()
	filmFields := schema.Film{}.Fields()
	_ = filmFields
	// filmDescStatus is the schema descriptor for status field.
	filmDescStatus := filmMixinFields0[1].Descriptor()
	// film.DefaultStatus holds the default value on creation for the status field.
	film.DefaultStatus = filmDescStatus.Default.(int8)
	// filmDescCreatedAt is the schema descriptor for created_at field.
	filmDescCreatedAt := filmMixinFields1[0].Descriptor()
	// film.DefaultCreatedAt holds the default value on creation for the created_at field.
	film.DefaultCreatedAt = filmDescCreatedAt.Default.(func() time.Time)
	// filmDescUpdatedAt is the schema descriptor for updated_at field.
	filmDescUpdatedAt := filmMixinFields1[1].Descriptor()
	// film.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	film.DefaultUpdatedAt = filmDescUpdatedAt.Default.(func() time.Time)
	// film.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	film.UpdateDefaultUpdatedAt = filmDescUpdatedAt.UpdateDefault.(func() time.Time)
}
