// Code generated by entc, DO NOT EDIT.

package film

import (
	"time"
)

const (
	// Label holds the string label denoting the film type in the database.
	Label = "film"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"

	// EdgeAuthors holds the string denoting the authors edge name in mutations.
	EdgeAuthors = "authors"

	// Table holds the table name of the film in the database.
	Table = "films"
	// AuthorsTable is the table the holds the authors relation/edge. The primary key declared below.
	AuthorsTable = "film_authors"
	// AuthorsInverseTable is the table name for the Author entity.
	// It exists in this package in order to avoid circular dependency with the "author" package.
	AuthorsInverseTable = "authors"
)

// Columns holds all SQL columns for film fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTitle,
	FieldDescription,
}

var (
	// AuthorsPrimaryKey and AuthorsColumn2 are the table columns denoting the
	// primary key for the authors relation (M2M).
	AuthorsPrimaryKey = []string{"film_id", "author_id"}
)

var (
	// DefaultStatus holds the default value on creation for the status field.
	DefaultStatus int8
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
)
