// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Author is the predicate function for author builders.
type Author func(*sql.Selector)

// Film is the predicate function for film builders.
type Film func(*sql.Selector)
